import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.sass"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export const ffDinPrimary = localFont({
    src: "./font/primary/din-rounded-regular.otf",
})

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={ffDinPrimary.className}>{children}</body>
        </html>
    )
}
