import type { Metadata } from "next"
import localFont from "next/font/local"
import {
    ClerkProvider,
    SignInButton,
    SignedIn,
    SignedOut,
    UserButton,
} from "@clerk/nextjs"

import "./globals.css"

export const metadata: Metadata = {
    title: "Duolingo",
    description: "Generated by create next app",
}

export const ffDinPrimary = localFont({
    src: "./font/primary/din-rounded-regular.otf",
})

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ClerkProvider>
            <html lang='en'>
                <body className={ffDinPrimary.className}>{children}</body>
            </html>
        </ClerkProvider>
    )
}
